### ISSUE TITLE
프로젝트 재설정.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-ble#17]
BLE 이해가 부족해서 구조 설정이 잘못됐다. 다시 만들어야겠다.

## TODO

- [x] `Connection`이 `BluetoothBleGatt` 래퍼로 작동하도록 수정.
- [ ] 커넥션 생성시에 노티피케이션, 이디케이션 구독 시작.
- [ ] 캐릭터리스틱에 `StateFlow`로 데이터 추가.
- [ ] UI 구조 재정립.

## 참고

- https://github.com/Beepiz/BleGattCoroutines
