### ISSUE TITLE
디바이스 스펙 로딩.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-ble#2]
프로세서에서 `assigned_numbers/core/class_of_device.yaml` 로딩.

## TODO

- [x] "2.8.1 Major Service Classes" 읽기.
- [x] "2.8.2 Major Device Class" 읽기.
- [x] `ble-spec` 접근 테스트 유틸리티.

## 참고

- #1 에서 분리.
- [Assigned Numbers Document (PDF)](https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Assigned_Numbers/out/en/Assigned_Numbers.pdf?v=1717593908991) > "2.8 Class of Device"
