### ISSUE TITLE
블루투스 장치 검색 권한 요청.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-ble#5]
샘플 앱을 실행할 때, 주변 블루투스 장치를 검색할 권한 요청하기.

## TODO

- [x] 스플래시, 권한 요청, 메인 화면 추가.
- [x] 스캔 권한이 없으면 스플래시에서 권한 요청 화면으로 이동.
- [x] 스캔 권한이 있으면 스플래시에서 메인 화면으로 이동.
- [x] 스캔 권한 요청을 거부하면 재요청 혹은 앱 설정으로 이동.
